name: Check latest install
on:
  workflow_call

jobs:
  pypi:
    name: Install from PyPI
     runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ${{ fromJSON(vars.SUPPORTED_PYTHON_VERSIONS) }}
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Check PyPI installation
        run: pip install acoular
      - name: Run smoke tests
        uses: acoular/ci/.github/actions/smoke-tests@main
        with:
          command: ''

  conda:
    name: Install from Anaconda
     runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Create environment
        run: conda create -n acoular python=${{ matrix.python-version }}
      - name: Check Anaconda installation
        run: conda run -n acoular conda install acoular::acoular
      - name: Run smoke tests
        uses: acoular/ci/.github/actions/smoke-tests@main
        with:
          command: 'conda run -n acoular'
