name: Check latest install
on:
  workflow_call

jobs:
  pypi:
    name: Install from PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ vars.LATEST_PYTHON_VERSION }}
      - name: Check PyPI installation
        run: pip install acoular
      - name: Run smoke tests
        uses: acoular/ci/.github/actions/smoke-tests@main
        with:
          command: ''
