name: Check latest install
on:
  workflow_call

jobs:
  pypi:
    name: Install from PyPI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ${{ fromJSON(vars.SUPPORTED_PYTHON_VERSIONS) }}
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Check PyPI installation
        run: pip install acoular
      - name: Run smoke tests
        uses: acoular/ci/.github/actions/smoke-tests@main
        with:
          command: ''

  conda:
    name: Install from Anaconda
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ${{ fromJSON(vars.SUPPORTED_PYTHON_VERSIONS) }}
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: acoular
          channels: acoular
      - name: Check Anaconda installation
        run: conda install acoular
      - name: Run smoke tests
        uses: acoular/ci/.github/actions/smoke-tests@main
        with:
          command: ''
